// Code generated by go generate; DO NOT EDIT.
// This file was generated by ./cmd/reset/main.go

package mock

type Resetter interface {
	Reset()
}

func hasReset(v interface{}) bool {
	_, ok := v.(Resetter)
	return ok
}

func (r *ResetableStruct) Reset() {
	if r == nil {
		return
	}
	r.i = 0
	r.str = ""
	if r.strP != nil {
		*r.strP = ""
	}
	if r.intP != nil {
		*r.intP = 0
	}
	if r.boolP != nil {
		*r.boolP = false
	}
	r.s = r.s[:0]
	clear(r.m)
	if r.child != nil && hasReset(r.child) {
		r.child.Reset()
	}
	if r.childWithReset != nil && hasReset(r.childWithReset) {
		r.childWithReset.Reset()
	}
}
