package main

import (
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"log"
	"os"
	"path/filepath"
	"strings"
)

func main() {
	root := "."

	if err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if !info.IsDir() && filepath.Ext(path) == ".go" {
			scanFile(path)
		}
		return nil
	}); err != nil {
		log.Fatal(err)
	}
}

func scanFile(filename string) {
	fset := token.NewFileSet()
	node, err := parser.ParseFile(fset, filename, nil, parser.ParseComments)
	if err != nil {
		log.Printf("%s parsing error: %v", filename, err)
		return
	}

	for _, decl := range node.Decls {
		if genDecl, ok := decl.(*ast.GenDecl); ok && genDecl.Tok == token.TYPE {
			for _, spec := range genDecl.Specs {
				if typeSpec, ok := spec.(*ast.TypeSpec); ok {
					if structType, ok := typeSpec.Type.(*ast.StructType); ok {
						if hasGenerateResetComment(genDecl) {
							pos := fset.Position(typeSpec.Pos())

							fileTemplate, err := generateResetFileTemplate(structType, node, typeSpec)
							if err != nil {
								panic(err)
							}

							if err := os.WriteFile(genPath(pos.Filename), fileTemplate, 0644); err != nil {
								panic(err)
							}

							fmt.Printf("Generate for struct %s %s:%d:%d in %s - done \n",
								typeSpec.Name.Name, filepath.Base(filename), pos.Line, pos.Column, pos.Filename)
						}
					}
				}
			}
		}
	}
}

func genPath(inputPath string) string {
	dir := filepath.Dir(inputPath)
	base := filepath.Base(inputPath)
	name := strings.TrimSuffix(base, filepath.Ext(base))
	return filepath.Join(dir, name+".gen.go")
}

func hasGenerateResetComment(genDecl *ast.GenDecl) bool {
	if genDecl.Doc != nil {
		for _, c := range genDecl.Doc.List {
			if strings.HasPrefix(strings.TrimSpace(c.Text), "// generate:reset") {
				return true
			}
		}
	}

	return false
}

const ResetFileHeaderTMP = `// Code generated by go generate; DO NOT EDIT.
// This file was generated by ./cmd/reset/main.go

package %s

type Resetter interface {
    Reset()
}

func hasReset(v interface{}) bool {
    _, ok := v.(Resetter)
    return ok
}

func (r *%s) Reset() {
	if r == nil {
		return
	}
`

// generateResetFileTemplate generates Go source code for a Reset method implementation
// for the given struct type. The function analyzes the struct fields using go/ast
// and produces reset logic for common types using zero values or appropriate clearing.
//
// Supported types in switch statement (switch t := field.Type.(type)):
//   - *ast.Ident: basic types (string="", int=0, bool=false, etc.) and custom types
//   - *ast.ArrayType: slices (truncated to zero length)
//   - *ast.MapType: maps (cleared with clear())
//   - *ast.StarExpr: pointers with nil checks and Reset() calls for custom pointer types
//
// Unsupported/commented types (require special handling):
//   - *ast.SliceExpr: represents slice OPERATIONS (e.g., data[1:10]), not slice types
//   - *ast.SelectorExpr: qualified types from other packages (time.Time, context.Context, sync.Mutex)
//   - *ast.InterfaceType: interface types (interface{}, io.Reader)
//   - *ast.ChanType: channel types (chan int, <-chan string)
//
// For unsupported types, zero values are not generated (empty case).
// Custom types in pointers attempt Reset() call if hasReset() available.
// Extend switch with additional cases for full type coverage.
func generateResetFileTemplate(structType *ast.StructType, node *ast.File, typeSpec *ast.TypeSpec) ([]byte, error) {
	var sb strings.Builder

	if _, err := fmt.Fprintf(&sb, ResetFileHeaderTMP, node.Name.Name, typeSpec.Name.Name); err != nil {
		return nil, err
	}

	for _, field := range structType.Fields.List {
		switch t := field.Type.(type) {
		case *ast.Ident:
			switch t.Name {
			case "string":
				if _, err := fmt.Fprintf(&sb, "r.%s = \"\"\n", field.Names[0]); err != nil {
					return nil, err
				}
			case "int", "int8", "int16", "int32", "int64", "uint", "uint8", "uint16", "uint32", "uint64", "uintptr",
				"float32", "float64", "complex64", "complex128", "byte", "rune":
				if _, err := fmt.Fprintf(&sb, "r.%s = 0\n", field.Names[0]); err != nil {
					return nil, err
				}
			case "bool":
				if _, err := fmt.Fprintf(&sb, "r.%s = false\n", field.Names[0]); err != nil {
					return nil, err
				}
			default: // custom types: type MyString string, type MyStruct struct etc
			}
		case *ast.ArrayType:
			if t.Len == nil {
				// if len == nil, that slice
				if _, err := fmt.Fprintf(&sb, "r.%s = r.%s[:0]\n", field.Names[0], field.Names[0]); err != nil {
					return nil, err
				}
			}
		case *ast.MapType:
			if _, err := fmt.Fprintf(&sb, "clear(r.%s)\n", field.Names[0].Name); err != nil {
				return nil, err
			}
		case *ast.StarExpr:
			// pointers
			if _, err := fmt.Fprint(&sb, generateIdentStarExprReset(t.X, field.Names[0].Name)); err != nil {
				return nil, err
			}
		default:
			return nil, fmt.Errorf("unknown type %T: %v\n", field.Type, field.Type)
		}
	}

	if _, err := fmt.Fprint(&sb, "}\n\n"); err != nil {
		return nil, err
	}

	return format.Source([]byte(sb.String()))
}

func generateIdentStarExprReset(elemType ast.Expr, fieldName string) string {
	switch elem := elemType.(type) {
	case *ast.Ident:
		switch elem.Name {
		case "string":
			return fmt.Sprintf("if r.%s != nil {\n*r.%s = \"\"\n}\n", fieldName, fieldName)
		case "int", "int8", "int16", "int32", "int64",
			"uint", "uint8", "uint16", "uint32", "uint64":
			return fmt.Sprintf("if r.%s != nil {\n*r.%s = 0\n}\n", fieldName, fieldName)
		case "bool":
			return fmt.Sprintf("if r.%s != nil {\n*r.%s = false\n}\n", fieldName, fieldName)
		default:
			return fmt.Sprintf("if r.%s != nil && hasReset(r.%s) {\nr.%s.Reset()\n}\n", fieldName, fieldName, fieldName)
		}
	default:
		return fmt.Sprintf("r.%s = nil\n", fieldName)
	}
}
