// Code generated by MockGen. DO NOT EDIT.
// Source: internal/handler/metrics.go

// Package service is a generated GoMock package.
package service

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/ibeloyar/metrics/internal/model"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetMetric mocks base method.
func (m *MockService) GetMetric(name string) (*model.Metrics, *model.APIError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetric", name)
	ret0, _ := ret[0].(*model.Metrics)
	ret1, _ := ret[1].(*model.APIError)
	return ret0, ret1
}

// GetMetric indicates an expected call of GetMetric.
func (mr *MockServiceMockRecorder) GetMetric(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetric", reflect.TypeOf((*MockService)(nil).GetMetric), name)
}

// GetMetrics mocks base method.
func (m *MockService) GetMetrics() ([]model.Metrics, *model.APIError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetrics")
	ret0, _ := ret[0].([]model.Metrics)
	ret1, _ := ret[1].(*model.APIError)
	return ret0, ret1
}

// GetMetrics indicates an expected call of GetMetrics.
func (mr *MockServiceMockRecorder) GetMetrics() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetrics", reflect.TypeOf((*MockService)(nil).GetMetrics))
}

// IsValidMetricType mocks base method.
func (m *MockService) IsValidMetricType(metricType string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsValidMetricType", metricType)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsValidMetricType indicates an expected call of IsValidMetricType.
func (mr *MockServiceMockRecorder) IsValidMetricType(metricType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsValidMetricType", reflect.TypeOf((*MockService)(nil).IsValidMetricType), metricType)
}

// Ping mocks base method.
func (m *MockService) Ping() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping")
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockServiceMockRecorder) Ping() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockService)(nil).Ping))
}

// SetMetric mocks base method.
func (m *MockService) SetMetric(metric *model.Metrics) *model.APIError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMetric", metric)
	ret0, _ := ret[0].(*model.APIError)
	return ret0
}

// SetMetric indicates an expected call of SetMetric.
func (mr *MockServiceMockRecorder) SetMetric(metric interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMetric", reflect.TypeOf((*MockService)(nil).SetMetric), metric)
}

// SetMetrics mocks base method.
func (m *MockService) SetMetrics(metrics []model.Metrics, remoteAddr string) *model.APIError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMetrics", metrics, remoteAddr)
	ret0, _ := ret[0].(*model.APIError)
	return ret0
}

// SetMetrics indicates an expected call of SetMetrics.
func (mr *MockServiceMockRecorder) SetMetrics(metrics, remoteAddr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMetrics", reflect.TypeOf((*MockService)(nil).SetMetrics), metrics, remoteAddr)
}

// ValidateMetric mocks base method.
func (m *MockService) ValidateMetric(metric model.Metrics) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateMetric", metric)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateMetric indicates an expected call of ValidateMetric.
func (mr *MockServiceMockRecorder) ValidateMetric(metric interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateMetric", reflect.TypeOf((*MockService)(nil).ValidateMetric), metric)
}

// ValidateMetrics mocks base method.
func (m *MockService) ValidateMetrics(metrics []model.Metrics) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateMetrics", metrics)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateMetrics indicates an expected call of ValidateMetrics.
func (mr *MockServiceMockRecorder) ValidateMetrics(metrics interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateMetrics", reflect.TypeOf((*MockService)(nil).ValidateMetrics), metrics)
}
